
export interface QuestTemplate {
    _id?: string;
    name: string;
    description?: string;
    stat: 'strength' | 'agility' | 'vitality' | 'intelligence' | 'sense';
    target: number;
    unit?: string;
    statReward: number;
    xpReward: number;
    category: 'daily_strength' | 'other';
    hasTextInput?: boolean; 
}



export const DAILY_STRENGTH_QUESTS: Omit<QuestTemplate, '_id'>[] = [
    {
        name: 'Push-ups',
        stat: 'strength',
        target: 20,
        unit: 'reps',
        statReward: 1,
        xpReward: 25,
        category: 'daily_strength',
    },
    {
        name: 'Sit-ups',
        stat: 'strength',
        target: 20,
        unit: 'reps',
        statReward: 1,
        xpReward: 25,
        category: 'daily_strength',
    },
    {
        name: 'Plank',
        stat: 'strength',
        target: 60,
        unit: 'seconds',
        statReward: 1,
        xpReward: 25,
        category: 'daily_strength',
    },
    {
        name: 'Squats',
        stat: 'strength',
        target: 50,
        unit: 'reps',
        statReward: 1,
        xpReward: 25,
        category: 'daily_strength',
    }
];

export const AGILITY_QUESTS: QuestTemplate[] = [
    {
        _id: 'agility-1', 
        name: 'Jumping Jacks',
        description: 'Do 30 Jumping Jacks to freshen up your body!',
        stat: 'agility',
        target: 30,
        unit: 'reps',
        statReward: 2,
        xpReward: 25,
        category: 'other',
    },
    {
        _id: 'agility-2',
        name: 'Balance Drill',
        stat: 'agility',
        description: 'Stand on one leg for 30 seconds to increase balance',
        target: 30,
        unit: 'seconds',
        statReward: 3,
        xpReward: 30,
        category: 'other',
    },
    {
        _id: 'agility-3',
        name: 'Quick Feet',
        description: 'Raise your legs while laying down and attempt to tap your feet for 60 seconds to enhance your reflexes! ',
        stat: 'agility',
        target: 60,
        unit: 'seconds',
        statReward: 3,
        xpReward: 30,
        category: 'other',
        
    },
    {
        _id: 'agility-4',
        name: 'High Knees',
        description: 'Do High Knees in place for 45 seconds to boost agility and coordination!',
        stat: 'agility',
        target: 45,
        unit: 'seconds',
        statReward: 3,
        xpReward: 30,
        category: 'other',
    
    },
    {
        _id: 'agility-5',
        name: 'Side Steps',
        description: 'Step quickly side to side in place for 60 seconds to improve footwork!',
        stat: 'agility',
        target: 60,
        unit: 'seconds',
        statReward: 3,
        xpReward: 30,
        category: 'other',
        
    },
    {_id: 'agility-6',
        name: 'Squat Pulses',
        description: 'Hold a half squat and pulse up and down 20 times to build leg agility!',
        stat: 'agility',
        target: 20,
        unit: 'reps',
        statReward: 2,
        xpReward: 25,
        category: 'other',
        
    },
    {_id: 'agility-7',
        name: 'Heel Raises',
        description: 'Rise onto your toes and lower back down 25 times to sharpen balance and agility!',
        stat: 'agility',
        target: 25,
        unit: 'reps',
        statReward: 2,
        xpReward: 25,
        category: 'other',
        
    },
    {_id: 'agility-8',
        name: 'Toe Taps',
        description: 'Tap your toes quickly on the ground for 45 seconds to train light feet!',
        stat: 'agility',
        target: 45,
        unit: 'seconds',
        statReward: 2,
        xpReward: 25,
        category: 'other',
        
    },
    {_id: 'agility-9',
        name: 'Fast Skips',
        description: 'Skip in place as quickly as you can for 30 seconds to boost coordination!',
        stat: 'agility',
        target: 30,
        unit: 'seconds',
        statReward: 3,
        xpReward: 30,
        category: 'other',
        
    },
    {_id: 'agility-10',
        name: 'Twist Jumps',
        description: 'Jump lightly while twisting your hips side to side for 20 reps to train balance and quickness!',
        stat: 'agility',
        target: 20,
        unit: 'reps',
        statReward: 3,
        xpReward: 30,
        category: 'other',
        
    },
    {_id: 'agility-11',
        name: 'Shuffle Drill',
        description: 'Quickly shuffle left and right in a small space for 30 seconds to sharpen your agility!',
        stat: 'agility',
        target: 30,
        unit: 'seconds',
        statReward: 3,
        xpReward: 30,
        category: 'other',
        
    },
    {_id: 'agility-12',
        name: 'Hop Switch',
        description: 'Hop forward and backward on one foot 15 times, then switch feet!',
        stat: 'agility',
        target: 30,
        unit: 'reps',
        statReward: 3,
        xpReward: 30,
        category: 'other',
        
    }
];


export const VITALITY_QUESTS: QuestTemplate[] = [
    {_id: 'vitality-1',
        name: 'Drink Water',
        stat: 'vitality',
        target: 5000,
        unit: 'ml',
        statReward: 2,
        xpReward: 25,
        category: 'daily_strength',
        
    },
    { _id: 'vitality-12',name: 'Morning Walk', description: 'Walk 2,000 steps.', stat: 'vitality', target: 2000, unit: 'steps', statReward: 2, xpReward: 25, category: 'other'},
    { _id: 'vitality-2',name: 'Healthy Meal', description: 'Eat a balanced meal.', stat: 'vitality', target: 1, unit: 'meal', statReward: 3, xpReward: 30, category: 'other'},
    { _id: 'vitality-3',name: 'Deep Breathing', description: 'Practice deep breathing for 5 minutes.', stat: 'vitality', target: 5, unit: 'minutes', statReward: 2, xpReward: 20, category: 'other'},
    { _id: 'vitality-4',name: 'Stretching', description: 'Stretch your full body for 10 minutes.', stat: 'vitality', target: 10, unit: 'minutes', statReward: 2, xpReward: 25, category: 'other'},
    { _id: 'vitality-5',name: 'Cardio Burst', description: 'Do 3 minutes of fast-paced cardio.', stat: 'vitality', target: 3, unit: 'minutes', statReward: 3, xpReward: 30, category: 'other'},
    { _id: 'vitality-6',name: 'Take a Cold Shower', description: 'Take a Cold Shower to release that stress.', stat: 'vitality', target: 10, unit: 'minutes', statReward: 1, xpReward: 15, category: 'other'},
    { _id: 'vitality-7',name: 'Fruit Snack', description: 'Eat a healthy fruit serving.', stat: 'vitality', target: 1, unit: 'serving', statReward: 1, xpReward: 15, category: 'other'},
    { _id: 'vitality-8',name: 'Water Challenge', description: 'Drink 1 liter of water.', stat: 'vitality', target: 1000, unit: 'ml', statReward: 3, xpReward: 30, category: 'other'},
    { _id: 'vitality-9',name: 'Sleep Well', description: 'Get at least 7 hours of sleep.', stat: 'vitality', target: 7, unit: 'hours', statReward: 3, xpReward: 40, category: 'other'},
    { _id: 'vitality-10',name: 'Short Jog', description: 'Jog for 10 minutes.', stat: 'vitality', target: 10, unit: 'minutes', statReward: 3, xpReward: 35, category: 'other'},
    { _id: 'vitality-11',name: 'Full Body Movement', description: 'Move continuously for 15 minutes.', stat: 'vitality', target: 15, unit: 'minutes', statReward: 3, xpReward: 35, category: 'other'}
];


export const INTELLIGENCE_QUESTS: QuestTemplate[] = [
    {_id: 'intelligence-1',
        name: 'Learn a New Word',
        stat: 'intelligence',
        description: 'Learn 5 new vocabulary words!',
        target: 5,
        unit: 'words',
        statReward: 2,
        xpReward: 20,
        category: 'other',
        hasTextInput: true
    },
    {_id: 'intelligence-2',
        name: 'Play Worlde for Today',
        stat: 'intelligence',
        description: 'Test out your knowledge of words by trying Worlde for today!',
        target: 6,
        unit: 'words',
        statReward: 1,
        xpReward: 10,
        category: 'other',
    },
    { _id: 'intelligence-3',name: 'Puzzle Time', description: 'Solve a logic puzzle.', stat: 'intelligence', target: 1, unit: 'puzzle', statReward: 2, xpReward: 25, category: 'other'},
    {_id: 'intelligence-4', name: 'Memory Exercise', description: 'Memorize a short poem or a new phrase!.', stat: 'intelligence', target: 1, unit: 'exercise', statReward: 2, xpReward: 25, category: 'other'},
    { _id: 'intelligence-5',name: 'Math Drill', description: 'Solve 10 math problems.', stat: 'intelligence', target: 10, unit: 'problems', statReward: 2, xpReward: 25, category: 'other'},
    { _id: 'intelligence-6',name: 'Learn a Fact', description: 'Read and remember one interesting fact.', stat: 'intelligence', target: 1, unit: 'fact', statReward: 1, xpReward: 15, category: 'other', hasTextInput: true
},
    { _id: 'intelligence-7',name: 'Brain Teaser', description: 'Complete a short brain teaser.', stat: 'intelligence', target: 1, unit: 'exercise', statReward: 2, xpReward: 20, category: 'other'},
    { _id: 'intelligence-8',name: 'Coding Practice', description: 'Write a small code snippet or algorithm.', stat: 'intelligence', target: 1, unit: 'exercise', statReward: 3, xpReward: 35, category: 'other'},
    { _id: 'intelligence-9',name: 'Language Exercise', description: 'Practice a new language for 10 minutes.', stat: 'intelligence', target: 10, unit: 'minutes', statReward: 2, xpReward: 25, category: 'other'},
    { _id: 'intelligence-10',name: 'Critical Thinking', description: 'Analyze a news article critically.', stat: 'intelligence', target: 1, unit: 'article', statReward: 2, xpReward: 25, category: 'other'},
    { _id: 'intelligence-11',name: 'Memory Recall', description: 'Recall and write 10 things you learned today.', stat: 'intelligence', target: 10, unit: 'items', statReward: 2, xpReward: 25, category: 'other', hasTextInput: true
},
    {_id: 'intelligence-12', name: 'Strategy Game', description: 'Play a strategy game for 15 minutes.', stat: 'intelligence', target: 15, unit: 'minutes', statReward: 3, xpReward: 30, category: 'other'}
];


export const SENSE_QUESTS: QuestTemplate[] = [
    {_id: 'sense-1',
        name: 'Meditation',
        stat: 'sense',
        description: 'Take a deep moment to yourself and relax.',
        target: 5,
        unit: 'minutes',
        statReward: 2,
        xpReward: 50,
        category: 'other',
        
    },
    {_id: 'sense-2',
        name: 'Gratitude List',
        description: 'Write somethings that you are grateful for in your life! It can be anything. ',
        stat: 'sense',
        target: 100,
        unit: 'words',
        statReward: 2,
        xpReward: 50,
        category: 'other',
        hasTextInput: true

    },
    {_id: 'sense-3',
        name: 'Nature Observation',
        description: 'Enjoy the be',
        stat: 'sense',
        target: 10,
        unit: 'minutes',
        statReward: 2,
        xpReward: 100,
        category: 'other',
    },
    {_id: 'sense-4',
        name: 'Breathing Exercises',
        description: 'Give yourself time to relax. Remember to breathe in, and breathe out.',
        stat: 'sense',
        target: 30,
        unit: 'seconds',
        statReward: 2,
        xpReward: 25,
        category: 'other',
        
    },
    {_id: 'sense-5',
        name: 'Stressful Moments in Your Life',
        description: 'Experiencing any stressful moments currently in your life? Release your stress and let it all out here.',
        stat: 'sense',
        target: 100,
        unit: 'words',
        statReward: 2,
        xpReward: 25,
        category: 'other',
        hasTextInput: true
    },
    {_id: 'sense-6',
        name: ' Check-In Journal',
        description: 'How are you doing in life as of right now? ',
        stat: 'sense',
        target: 100,
        unit: 'words',
        statReward: 2,
        xpReward: 25,
        category: 'other',
        hasTextInput: true
    },
    {_id: 'sense-7',
        name: 'Reflective Writing',
        description: 'Reflect on your day in 5 sentences.',
        stat: 'sense',
        target: 5,
        unit: 'sentences',
        statReward: 2,
        xpReward: 25,
        category: 'other',
        hasTextInput: true
    },
    {_id: 'sense-8',
        name: 'Affirmations',
        description: 'Say 5 positive affirmations to your relatives or friends!',
        stat: 'sense',
        target: 5,
        unit: 'affirmations',
        statReward: 1,
        xpReward: 15,
        category: 'other',
        hasTextInput: true
    },
    {_id: 'sense-9',
        name: 'Progress Check',
        description: 'Write your weekly progress for 5 minutes.',
        stat: 'sense',
        target: 10,
        unit: 'minutes',
        statReward: 2,
        xpReward: 25,
        category: 'other',
        hasTextInput: true
    },
    {_id: 'sense-10',
        name: 'Digital Detox',
        description: 'Stay off your phone for 30 minutes.',
        stat: 'sense',
        target: 30,
        unit: 'minutes',
        statReward: 2,
        xpReward: 35,
        category: 'other', 
    }
];


